# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='illustration',
            name='Imgname',
        ),
    ]
